export default [{
    upper: '~',
    lower: '`',
    code: 'Backquote',
}, {
    upper: '!',
    lower: '1',
    code: 'Digit1',
}, {
    upper: '@',
    lower: '2',
    code: 'Digit2',
}, {
    upper: '#',
    lower: '3',
    code: 'Digit3',
}, {
    upper: '$',
    lower: '4',
    code: 'Digit4',
}, {
    upper: '%',
    lower: '5',
    code: 'Digit5',
}, {
    upper: '^',
    lower: '6',
    code: 'Digit6',
}, {
    upper: '&',
    lower: '7',
    code: 'Digit7',
}, {
    upper: '*',
    lower: '8',
    code: 'Digit8',
}, {
    upper: '(',
    lower: '9',
    code: 'Digit9',
}, {
    upper: ')',
    lower: '0',
    code: 'Digit0',
}, {
    upper: '_',
    lower: '-',
    code: 'Minus',
}, {
    upper: '+',
    lower: '=',
    code: 'Equal',
}, {
    upper: '|',
    lower: '\\',
    code: 'Backslash',
}, {
    upper: null,
    lower: 'Del',
    code: 'Delete',
}, {
    upper: null,
    lower: 'Tab',
    code: 'Tab',
}, {
    upper: 'Q',
    lower: 'q',
    code: 'KeyQ',
}, {
    upper: 'W',
    lower: 'w',
    code: 'KeyW',
}, {
    upper: 'E',
    lower: 'e',
    code: 'KeyE',
}, {
    upper: 'R',
    lower: 'r',
    code: 'KeyR',
}, {
    upper: 'T',
    lower: 't',
    code: 'KeyT',
}, {
    upper: 'Y',
    lower: 'y',
    code: 'KeyY',
}, {
    upper: 'U',
    lower: 'u',
    code: 'KeyU',
}, {
    upper: 'I',
    lower: 'i',
    code: 'KeyI',
}, {
    upper: 'O',
    lower: 'o',
    code: 'KeyO',
}, {
    upper: 'P',
    lower: 'p',
    code: 'KeyP',
}, {
    upper: '{',
    lower: '[',
    code: 'BracketLeft',
}, {
    upper: '}',
    lower: ']',
    code: 'BracketRight',
}, {
    upper: null,
    lower: 'Backspace',
    code: 'Backspace',
},{
    upper: null,
    lower: 'CapsLock',
    code: 'CapsLock',
}, {
    upper: 'A',
    lower: 'a',
    code: 'KeyA',
}, {
    upper: 'S',
    lower: 's',
    code: 'KeyS',
}, {
    upper: 'D',
    lower: 'd',
    code: 'KeyD',
}, {
    upper: 'F',
    lower: 'f',
    code: 'KeyF',
}, {
    upper: 'G',
    lower: 'g',
    code: 'KeyG',
}, {
    upper: 'H',
    lower: 'h',
    code: 'KeyH',
}, {
    upper: 'J',
    lower: 'j',
    code: 'KeyJ',
}, {
    upper: 'K',
    lower: 'k',
    code: 'KeyK',
}, {
    upper: 'L',
    lower: 'l',
    code: 'KeyL',
}, {
    upper: ':',
    lower: ';',
    code: 'Semicolon',
}, {
    upper: '"',
    lower: '\'',
    code: 'Quote',
}, {
    upper: null,
    lower: 'Enter',
    code: 'Enter',
}, {
    upper: null,
    lower: 'Shift',
    code: 'ShiftLeft',
}, {
    upper: 'Z',
    lower: 'z',
    code: 'KeyZ',
}, {
    upper: 'X',
    lower: 'x',
    code: 'KeyX',
}, {
    upper: 'C',
    lower: 'c',
    code: 'KeyC',
}, {
    upper: 'V',
    lower: 'v',
    code: 'KeyV',
}, {
    upper: 'B',
    lower: 'b',
    code: 'KeyB',
}, {
    upper: 'N',
    lower: 'n',
    code: 'KeyN',
}, {
    upper: 'M',
    lower: 'm',
    code: 'KeyM',
}, {
    upper: '<',
    lower: ',',
    code: 'Comma',
}, {
    upper: '>',
    lower: '.',
    code: 'Period',
}, {
    upper: '?',
    lower: '/',
    code: 'Slash',
}, {
    upper: null,
    lower: '&uarr;',
    code: 'ArrowUp',
}, {
    upper: null,
    lower: 'Shift',
    code: 'ShiftRight',
}, {
    upper: null,
    lower: 'Ctrl',
    code: 'ControlLeft',
}, {
    upper: null,
    lower: 'EN',
    code: 'SwitchLang',
},{
    upper: null,
    lower: 'Alt',
    code: 'AltLeft',
}, {
    upper: null,
    lower: 'Voice',
    code: 'VoiceDial',
},{
    upper: ' ',
    lower: ' ',
    code: 'Space',
}, {
    upper: null,
    lower: 'Alt',
    code: 'AltRight',
}, {
    upper: null,
    lower: 'Ctrl',
    code: 'ControlRight',
}, {
    upper: null,
    lower: '&larr;',
    code: 'ArrowLeft',
}, {
    upper: null,
    lower: '&darr;',
    code: 'ArrowDown',
}, {
    upper: null,
    lower: '&rarr;',
    code: 'ArrowRight',
}, {
    upper: null,
    lower: '&#9835;',
    code: 'Sound',
}];
